<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Group
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: manifest.php 7562 2010-10-05 22:17:24Z john $
 * @author     John
 */
return array(
  '4.0.5' => array(
    'controllers/MemberController.php' => 'Added support for missing action and notification types; join form now shows RSVP options',
    'controllers/TopicController.php' => 'Added topic watching support',
    'externals/images/nophoto_group_thumb_icon.png' => 'Changed',
    'externals/images/unwatch.png' => 'Added',
    'externals/images/watch.png' => 'Added',
    'externals/styles/main.css' => 'Added styles',
    'Form/Admin/Settings/Level.php' => 'Fixed typo in option labels',
    'Form/Create.php' => 'Added missing .jpeg extension to allowed file types',
    'Form/Edit.php' => 'Added missing .jpeg extension to allowed file types',
    'Form/Post/Create.php' => 'Added topic watching support',
    'Form/Post/Edit.php' => 'Added topic watching support',
    'Form/Topic/Create.php' => 'Added topic watching support',
    'Model/DbTable/TopicWatches.php' => 'Added',
    'Model/Group.php' => 'Fixed incorrect argument to getParent function',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support',
    'settings/changelog.php' => 'Added',
    'settings/install.php' => 'Code formatting',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.4-4.0.5.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/topic/view.tpl' => 'Added topic watching support',
    '/application/languages/en/group.csv' => 'Added missing phrases',
  ),
  '4.0.4' => array(
    'Api/Core.php' => 'Added category ordering',
    'controllers/TopicController.php' => 'Improving auth checking',
    'externals/styles/main.css' => 'Improved RTL support',
    'Form/Post/Delete.php' => 'Style tweak',
    'Form/Post/Edit.php' => 'Style tweak',
    'Form/Topic/Delete.php' => 'Style tweak',
    'Form/Topic/Rename.php' => 'Style tweak',
    'Plugin/Core.php' => 'Fixed issues with privacy in the feed when content is hidden from the public by admin settings',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/install.php' => 'Group page should not be considered a custom page',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added; fixed typo in permissions table leftover from several versions ago; fixed custom page setting',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/photo/view.tpl' => 'Added missing translation',
    'widgets/profile-discussions/*' => 'Added correct auth checking for showing link',
    'widgets/profile-events/index.tpl' => 'Style tweak',
    '/application/languages/en/group.csv' => 'Added phrases',
  ),
  '4.0.3' => array(
    'controllers/GroupController.php' => 'Fixed bug in privacy for officers',
    'Model/Photo.php' => 'Fixed errors when deleting a photo with a missing file',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Added correct locale date format',
    'widgets/profile-groups/index.tpl' => 'Added missing translation',
    'widgets/profile-info/index.tpl' => 'Added missing translation',
    '/application/languages/en/group.csv' => 'Added phrases',
  ),
  '4.0.2' => array(
    'Api/Core.php' => 'Categories ordered by name',
    'controllers/AdminSettingsController.php' => 'Various level settings fixes and enhancements',
    'controllers/EventController.php' => 'Remove, no longer used',
    'controllers/GroupController.php' => 'Various level settings fixes and enhancements',
    'controllers/IndexController.php' => 'Various level settings fixes and enhancements',
    'externals/styles/main.css' => 'Styled the group events profile tab',
    'Form/Create.php' => 'Various level settings fixes and enhancements',
    'Form/Edit.php' => 'Various level settings fixes and enhancements',
    'Form/Admin/Level.php' => 'Moved',
    'Form/Admin/Settings/Level.php' => 'Various level settings fixes and enhancements',
    'Plugin/Core.php' => 'Added activity stream index type',
    'Plugin/Menus.php' => 'Fixed problem that would prevent the invite link from showing for non-officers when allowed',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added',
    'settings/my.sql' => 'Various level settings fixes and enhancements',
    'widgets/profile-events/Controller.php' => 'Tab now hides properly when the event plugin is not enabled',
    'widgets/profile-events/index.tpl' => 'Cleanup',
    'widgets/profile-groups/Controller.php' => 'Tab now shows properly when the event plugin is not enabled',
    'widgets/profile-members/index.tpl' => 'Search input text and owner/officer now translate',
  ),
  '4.0.1' => array(
    'Api/Core.php' => 'Better cleanup of temporary files',
    'controllers/AdminSettingsController.php' => 'Fixed problem in level select',
    'controllers/GroupController.php' => 'Added level permission for styles',
    'controllers/IndexController.php' => 'Added menu for group manage page',
    'controllers/PhotoController.php' => 'Added view count support',
    'controllers/TopicController.php' => 'Added view count support',
    'Form/Admin/Level.php' => 'Added level permission for styles',
    'Model/Group.php' => 'Better cleanup of temporary files',
    'Plugin/Core.php' => 'Query optimization',
    'Plugin/Menus.php' => 'Added level permission for styles',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.0-4.0.1.sql' => 'Added',
    'settings/my.sql' => 'Added view_count and comment_count columns to engine4_group_photos table; added view_count column to engine4_group_topics table; added default permissions for style permission',
    'widgets/profile-info/index.tpl' => 'Fixed possible bug when owner title is not set',
  ),
) ?>